name: "AWS Infrastructure"

on:
  push:
    branches:
      - feature/*
    paths:
      - terraform/infra/dev/*
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.48.0

      - name: Show TFLint Version
        run: tflint --version

      - name: Validate
        working-directory: terraform/infra/dev
        run: |
          tflint --format=compact --recursive --color --minimum-failure-severity=error

  security:
    name: Security
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Analysis
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
          working_directory: terraform/infra/dev

  plan:
    name: Plan
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs: security
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.5"

      - name: Terraform Init
        run: terraform -chdir=./terraform/infra/dev init

      - name: Terraform Plan
        run: terraform -chdir=./terraform/infra/dev plan

  apply:
    name: Apply
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs: plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.5"

      - name: Terraform Init
        run: terraform -chdir=./terraform/infra/dev init

      - name: Terraform Apply
        run: terraform -chdir=./terraform/infra/dev apply