name: "AWS Infrastructure"

on:
  push:
    branches:
      - feature/*
    paths:
      - terraform/infra/dev/*
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.48.0

      - name: Show TFLint Version
        run: tflint --version

      - name: Validate
        working-directory: terraform/infra/dev
        run: |
          tflint --format=compact --recursive --color --minimum-failure-severity=error

  security:
    name: Security
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Analysis
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
          working_directory: terraform/infra/dev

